name       : haskell-base-unicode-symbols
version    : 0.2.4.2
release    : 1
source     :
    - https://hackage.haskell.org/package/base-unicode-symbols-0.2.4.2/base-unicode-symbols-0.2.4.2.tar.gz : 4364d6c403616e9ec0c240c4cb450c66af43ea8483d73c315e96f4ba3cb97062
license    : BSD-3-Clause
component  : programming.haskell
summary    : Unicode alternatives for common functions and operators
description: |
    Unicode alternatives for common functions and operators
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
